/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => NotionBasesPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/constants.ts
var NOTION_TABLE_VIEW = "notion-table";
var LOG_PREFIX = "[good-bases]";

// src/view-options.ts
function buildViewOptions(_config) {
  return [
    {
      type: "property",
      key: "parentProperty",
      displayName: "Parent property name",
      default: "parent item"
    },
    {
      type: "toggle",
      key: "wrapCells",
      displayName: "Wrap all content",
      default: true
    },
    {
      type: "toggle",
      key: "verticalLines",
      displayName: "Show vertical lines",
      default: true
    },
    {
      type: "dropdown",
      key: "openMode",
      displayName: "Open notes in",
      default: "tab",
      options: {
        tab: "New tab",
        panel: "Page panel",
        split: "Side panel"
      }
    },
    {
      type: "multitext",
      key: "pillProperties",
      displayName: "Properties to show as colored pills"
    },
    {
      type: "multitext",
      key: "pinnedColors",
      displayName: "Pinned pill colors (value=color: gray, brown, orange, yellow, green, blue, purple, pink, red)"
    }
  ];
}

// src/view/notion-table-view.ts
var import_obsidian4 = require("obsidian");

// src/lib/colors.ts
var NOTION_COLORS = [
  { name: "gray", lightBg: "#EBECED", lightFg: "#9B9A97", darkBg: "#454B4E", darkFg: "rgba(151,154,155,0.95)" },
  { name: "brown", lightBg: "#E9E5E3", lightFg: "#64473A", darkBg: "#434040", darkFg: "#937264" },
  { name: "orange", lightBg: "#FAEBDD", lightFg: "#D9730D", darkBg: "#594A3A", darkFg: "#FFA344" },
  { name: "yellow", lightBg: "#FBF3DB", lightFg: "#DFAB01", darkBg: "#59563B", darkFg: "#FFDC49" },
  { name: "green", lightBg: "#DDEDEA", lightFg: "#0F7B6C", darkBg: "#354C4B", darkFg: "#4DAB9A" },
  { name: "blue", lightBg: "#DDEBF1", lightFg: "#0B6E99", darkBg: "#364954", darkFg: "#529CCA" },
  { name: "purple", lightBg: "#EAE4F2", lightFg: "#6940A5", darkBg: "#443F57", darkFg: "#9A6DD7" },
  { name: "pink", lightBg: "#F4DFEB", lightFg: "#AD1A72", darkBg: "#533B4C", darkFg: "#E255A1" },
  { name: "red", lightBg: "#FBE4E4", lightFg: "#E03E3E", darkBg: "#594141", darkFg: "#FF7369" }
];
function colorFor(text) {
  let h = 0;
  for (let i = 0; i < text.length; i++) {
    h = h * 31 + text.charCodeAt(i) >>> 0;
  }
  const vibrantColors = NOTION_COLORS.slice(1);
  return vibrantColors[h % vibrantColors.length];
}
function colorByName(name) {
  return NOTION_COLORS.find((c) => c.name === name);
}
function colorKey(text) {
  return text.replace(/^#/, "").toLowerCase();
}
function resolvePillColor(text, pinned) {
  const key = colorKey(text);
  return pinned.get(key) ?? colorFor(key);
}
function applyColorVars(el, c) {
  const bg = c.darkBg || c.lightBg;
  const fg = c.darkFg || c.lightFg;
  el.setCssProps({
    "--ntn-pill-bg-light": c.lightBg,
    "--ntn-pill-fg-light": c.lightFg,
    "--ntn-pill-bg-dark": bg,
    "--ntn-pill-fg-dark": fg
  });
  el.style.setProperty("background-color", bg, "important");
  el.style.setProperty("color", fg, "important");
}
function applyPillColor(pill, text, pinned) {
  const c = resolvePillColor(text, pinned);
  applyColorVars(pill, c);
  const bg = c.darkBg || c.lightBg;
  const fg = c.darkFg || c.lightFg;
  if (bg)
    pill.style.setProperty("background-color", bg, "important");
  if (fg)
    pill.style.setProperty("color", fg, "important");
}

// src/lib/pills.ts
var import_obsidian = require("obsidian");
function bareName(prop) {
  return prop.split(".").slice(1).join(".");
}
function computePillProps(props, entries, config, app) {
  const pillProps = /* @__PURE__ */ new Set();
  const listProps = /* @__PURE__ */ new Set();
  const userListed = config.get("pillProperties");
  const userSet = new Set(
    Array.isArray(userListed) ? userListed.map((s) => String(s).toLowerCase().trim()) : []
  );
  const mtm = app.metadataTypeManager;
  for (const prop of props) {
    const bare = bareName(prop).toLowerCase();
    const display = config.getDisplayName(prop).toLowerCase();
    const info = mtm?.getPropertyInfo?.(bare);
    const metaType = typeof info === "string" ? info : info?.widget ?? info?.type;
    let isList = metaType === "multitext" || metaType === "tags" || metaType === "aliases";
    if (!isList) {
      for (const entry of entries) {
        if (entry.getValue(prop) instanceof import_obsidian.ListValue) {
          isList = true;
          break;
        }
      }
    }
    if (!isList) {
      for (const entry of entries) {
        const val = entry.getValue(prop);
        if (val) {
          const s = String(val);
          if (s.includes("[[")) {
            pillProps.add(prop);
            break;
          }
        }
      }
    }
    if (isList)
      listProps.add(prop);
    if (isList || bare === "tags" || bare === "parent_item" || bare === "parent item" || bare === "parent" || bare === "year" || userSet.has(bare) || userSet.has(display)) {
      pillProps.add(prop);
    }
  }
  return { pillProps, listProps };
}
function parsePinnedColors(raw) {
  const pinned = /* @__PURE__ */ new Map();
  if (!Array.isArray(raw))
    return pinned;
  for (const item of raw) {
    const m = String(item).match(/^(.+?)\s*[=:]\s*(.+)$/);
    if (!m)
      continue;
    const value = m[1].trim().replace(/^#/, "").toLowerCase();
    const colorSpec = m[2].trim();
    if (colorSpec.includes("|") || colorSpec.startsWith("#")) {
      const parts = colorSpec.split("|");
      const bg = parts[0].trim();
      let fg = parts[1] ? parts[1].trim() : "#ffffff";
      if (fg === "white" || fg === "light")
        fg = "#ffffff";
      if (fg === "black" || fg === "dark")
        fg = "#111827";
      pinned.set(value, {
        name: "custom",
        lightBg: bg,
        lightFg: fg,
        darkBg: bg,
        darkFg: fg
      });
    } else {
      const color = colorByName(colorSpec.toLowerCase());
      if (value && color)
        pinned.set(value, color);
    }
  }
  return pinned;
}

// src/lib/values.ts
var import_obsidian2 = require("obsidian");
function valueToStrings(value) {
  if (value === null)
    return [];
  if (value instanceof import_obsidian2.ListValue) {
    const out = [];
    for (let i = 0; i < value.length(); i++) {
      const item = value.get(i);
      if (item) {
        const s2 = item.toString().trim();
        if (s2 && s2 !== "null" && s2 !== "undefined")
          out.push(s2);
      }
    }
    return out;
  }
  const s = value.toString().trim();
  return s && s !== "null" && s !== "undefined" ? [s] : [];
}

// src/view/note-modal.ts
var import_obsidian3 = require("obsidian");

// src/lib/frontmatter.ts
function splitFrontmatter(raw) {
  const match = raw.match(/^---\r?\n(?:[\s\S]*?\r?\n)?---(?:\r?\n|$)/);
  if (!match)
    return { frontmatter: "", body: raw };
  return { frontmatter: match[0], body: raw.slice(match[0].length) };
}

// src/view/note-modal.ts
var NotePageModal = class extends import_obsidian3.Modal {
  constructor(app, file, deps) {
    super(app);
    /** Lifetime owner for MarkdownRenderer children; replaced per render. */
    this.renderComp = null;
    this.saveTimer = null;
    /** True while the textarea holds keystrokes not yet written to disk. */
    this.dirty = false;
    this.file = file;
    this.deps = deps;
  }
  onOpen() {
    void this.buildPanel();
  }
  async buildPanel() {
    const { contentEl, modalEl } = this;
    modalEl.addClass("ntn-page-modal");
    contentEl.addClass("ntn-page-content");
    const openTabBtn = modalEl.createDiv({
      cls: "ntn-page-open-tab",
      attr: { "aria-label": "Open in new tab", tabindex: "0" }
    });
    (0, import_obsidian3.setIcon)(openTabBtn, "maximize-2");
    const openInTab = () => {
      this.close();
      void this.app.workspace.getLeaf(true).openFile(this.file);
    };
    openTabBtn.addEventListener("click", openInTab);
    openTabBtn.addEventListener("keydown", (evt) => {
      if (evt.key === "Enter" || evt.key === " ") {
        evt.preventDefault();
        openInTab();
      }
    });
    this.pageTitleEl = contentEl.createEl("h1", {
      cls: "ntn-page-title",
      // plaintext-only keeps pasted rich text from injecting HTML
      // (supported in Electron/Chromium, which is all Obsidian runs on).
      attr: { contenteditable: "plaintext-only", "data-placeholder": "Untitled" }
    });
    this.pageTitleEl.setText(this.file.basename);
    this.pageTitleEl.addEventListener("keydown", (evt) => {
      if (evt.key === "Enter") {
        evt.preventDefault();
        this.editBody();
      }
    });
    this.pageTitleEl.addEventListener("blur", () => void this.commitTitle());
    const { frontmatter, body } = splitFrontmatter(await this.app.vault.read(this.file));
    this.propsEl = contentEl.createDiv({ cls: "ntn-page-props" });
    this.renderPropertyRows(this.parseProperties(frontmatter));
    this.previewEl = contentEl.createDiv({
      cls: "ntn-page-preview markdown-rendered"
    });
    this.previewEl.addEventListener("click", (evt) => {
      const link = evt.target.closest("a");
      if (link?.hasClass("internal-link")) {
        evt.preventDefault();
        const target = link.getAttribute("data-href") ?? link.getAttribute("href") ?? "";
        this.close();
        void this.app.workspace.openLinkText(target, this.file.path, import_obsidian3.Keymap.isModEvent(evt));
        return;
      }
      if (link)
        return;
      this.editBody();
    });
    this.bodyArea = contentEl.createEl("textarea", {
      cls: "ntn-page-body ntn-hidden",
      attr: { placeholder: "Write something\u2026" }
    });
    this.bodyArea.value = body;
    this.bodyArea.addEventListener("input", () => {
      this.autoSizeBody();
      this.scheduleSave();
    });
    this.bodyArea.addEventListener("blur", () => {
      if (this.dirty)
        void this.saveBody();
      void this.showPreview();
    });
    await this.renderPreview();
    this.pageTitleEl.focus();
    contentEl.win.getSelection()?.selectAllChildren(this.pageTitleEl);
  }
  // ---------------- Body: preview <-> edit ----------------
  /** Swap the rendered body for the markdown textarea and focus it. */
  editBody() {
    this.previewEl.addClass("ntn-hidden");
    this.bodyArea.removeClass("ntn-hidden");
    this.autoSizeBody();
    this.bodyArea.focus();
  }
  /**
   * Grow the textarea to fit its content so the whole body stays readable
   * while editing — the panel scrolls, the textarea never does. Without
   * this, a long properties list plus the title can crush a flex-sized
   * textarea to nothing (many-properties bug, July 2026).
   */
  autoSizeBody() {
    this.bodyArea.setCssStyles({ height: "auto" });
    this.bodyArea.setCssStyles({ height: `${this.bodyArea.scrollHeight + 2}px` });
  }
  /** Swap the textarea back for the freshly rendered markdown. */
  async showPreview() {
    this.bodyArea.addClass("ntn-hidden");
    this.previewEl.removeClass("ntn-hidden");
    await this.renderPreview();
  }
  async renderPreview() {
    this.renderComp?.unload();
    this.renderComp = new import_obsidian3.Component();
    this.renderComp.load();
    this.previewEl.empty();
    const markdown = this.bodyArea.value;
    if (!markdown.trim()) {
      this.previewEl.createDiv({
        cls: "ntn-page-preview-empty",
        text: "Write something\u2026"
      });
      return;
    }
    await import_obsidian3.MarkdownRenderer.render(
      this.app,
      markdown,
      this.previewEl,
      this.file.path,
      this.renderComp
    );
  }
  // ---------------- Properties ----------------
  /** Re-read the file and rebuild the property rows from what's on disk. */
  async refreshProperties() {
    const { frontmatter } = splitFrontmatter(await this.app.vault.read(this.file));
    this.renderPropertyRows(this.parseProperties(frontmatter));
  }
  renderPropertyRows(props) {
    this.propsEl.empty();
    for (const [key, value] of Object.entries(props)) {
      this.renderPropertyRow(key, value);
    }
  }
  renderPropertyRow(key, value) {
    const row = this.propsEl.createDiv({ cls: "ntn-page-prop" });
    row.createDiv({ cls: "ntn-page-prop-name", text: key });
    const valueEl = row.createDiv({ cls: "ntn-page-prop-value" });
    const isPill = this.deps.isPillProp(key) || Array.isArray(value) || key === "parent_item" || key === "parent item" || key === "parent" || key === "year" || value && String(value).includes("[[");
    const editable = key !== "tags";
    if (isPill) {
      const items = Array.isArray(value) ? value.map((v) => this.formatScalar(v)) : this.isEmpty(value) ? [] : [this.formatScalar(value)];
      for (const item of items) {
        const pill = valueEl.createSpan({ cls: "ntn-pill" });
        this.deps.applyColor(pill, item);
        pill.setText(item.replace(/^#/, ""));
      }
      if (!items.length)
        this.renderEmpty(valueEl);
      if (editable) {
        valueEl.addClass("ntn-page-prop-editable");
        valueEl.addEventListener("click", () => {
          this.deps.openSelect({
            anchor: valueEl,
            file: this.file,
            propName: key,
            current: items,
            isList: this.deps.isListProp(key) || Array.isArray(value),
            onWrite: () => void this.refreshProperties()
          });
        });
        this.deps.reanchorSelect(valueEl, this.file.path, key);
      }
      return;
    }
    if (typeof value === "boolean") {
      const cb = valueEl.createEl("input", { type: "checkbox", cls: "ntn-checkbox" });
      cb.checked = value;
      cb.addEventListener("change", () => void this.writeAndRefresh(key, cb.checked));
      return;
    }
    if (this.isEmpty(value))
      this.renderEmpty(valueEl);
    else
      valueEl.createSpan({ text: this.formatScalar(value) });
    if (editable) {
      valueEl.addClass("ntn-page-prop-editable");
      valueEl.addEventListener("click", () => this.editScalar(valueEl, key, value));
    }
  }
  /** Swap a property row's value for an input; Enter/blur commits, Esc cancels. */
  editScalar(valueEl, key, value) {
    if (valueEl.querySelector(".ntn-input"))
      return;
    const kind = typeof value === "number" ? "number" : "text";
    const current = this.isEmpty(value) ? "" : this.formatScalar(value);
    valueEl.empty();
    const input = valueEl.createEl("input", {
      type: "text",
      cls: "ntn-input ntn-page-prop-input"
    });
    input.value = current;
    input.focus();
    input.select();
    let committed = false;
    const commit = () => {
      if (committed)
        return;
      committed = true;
      const raw = input.value.trim();
      if (raw === current) {
        void this.refreshProperties();
        return;
      }
      let out = raw;
      if (kind === "number") {
        const n = Number(raw);
        out = raw === "" ? null : Number.isNaN(n) ? raw : n;
      } else if (raw === "") {
        out = null;
      }
      void this.writeAndRefresh(key, out);
    };
    input.addEventListener("keydown", (evt) => {
      if (evt.key === "Enter") {
        evt.preventDefault();
        commit();
      } else if (evt.key === "Escape") {
        committed = true;
        evt.preventDefault();
        evt.stopPropagation();
        void this.refreshProperties();
      }
    });
    input.addEventListener("blur", commit);
  }
  async writeAndRefresh(propName, value) {
    await this.deps.write(this.file, propName, value);
    await this.refreshProperties();
  }
  parseProperties(frontmatter) {
    if (!frontmatter)
      return {};
    const yaml = frontmatter.replace(/^---\r?\n/, "").replace(/---\r?\n?$/, "");
    try {
      const parsed = (0, import_obsidian3.parseYaml)(yaml);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        return parsed;
      }
    } catch (e) {
      console.error(`${LOG_PREFIX} failed to parse note frontmatter`, e);
    }
    return {};
  }
  isEmpty(value) {
    return value === null || value === void 0 || value === "";
  }
  renderEmpty(valueEl) {
    valueEl.createSpan({ cls: "ntn-page-prop-empty", text: "Empty" });
  }
  /** YAML scalars as Notion would show them (dates as yyyy-mm-dd). */
  formatScalar(value) {
    if (value instanceof Date)
      return value.toISOString().slice(0, 10);
    return String(value);
  }
  // ---------------- Body ----------------
  /** Debounced autosave: write 400ms after the last keystroke. */
  scheduleSave() {
    this.dirty = true;
    const win = this.contentEl.win;
    if (this.saveTimer !== null)
      win.clearTimeout(this.saveTimer);
    this.saveTimer = win.setTimeout(() => void this.saveBody(), 400);
  }
  async saveBody() {
    this.dirty = false;
    try {
      await this.app.vault.process(
        this.file,
        (data) => splitFrontmatter(data).frontmatter + this.bodyArea.value
      );
    } catch (e) {
      console.error(`${LOG_PREFIX} failed to save note body`, e);
      new import_obsidian3.Notice("Couldn't save the note.");
    }
  }
  // ---------------- Title ----------------
  /** Rename the file to match the title; revert the h1 if that fails. */
  async commitTitle() {
    const title = (this.pageTitleEl.textContent ?? "").replace(/\s+/g, " ").trim();
    if (!title || title === this.file.basename)
      return;
    const folder = this.file.parent?.path ?? "";
    const newPath = folder && folder !== "/" ? `${folder}/${title}.md` : `${title}.md`;
    try {
      await this.app.fileManager.renameFile(this.file, newPath);
    } catch (e) {
      console.error(`${LOG_PREFIX} failed to rename note`, e);
      new import_obsidian3.Notice(`Couldn't rename the note to "${title}".`);
      this.pageTitleEl.setText(this.file.basename);
    }
  }
  onClose() {
    this.deps.closeSelect();
    this.renderComp?.unload();
    this.renderComp = null;
    if (this.saveTimer !== null)
      this.contentEl.win.clearTimeout(this.saveTimer);
    void this.flushPendingEdits();
    this.contentEl.empty();
  }
  async flushPendingEdits() {
    if (this.dirty)
      await this.saveBody();
    await this.commitTitle();
  }
};

// src/view/select-editor.ts
function cleanText(val) {
  if (!val)
    return "";
  return val.replace(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g, (_, target, alias) => {
    if (alias && alias.trim())
      return alias.trim();
    const t = target.trim();
    const lastSlash = t.lastIndexOf("/");
    let name = lastSlash !== -1 ? t.substring(lastSlash + 1) : t;
    if (name.toLowerCase().endsWith(".md"))
      name = name.slice(0, -3);
    return name;
  });
}
var SelectEditor = class {
  constructor(deps) {
    this.deps = deps;
    /** Open color-picker flyout, if any (a sibling popover on the body). */
    this.colorMenu = null;
    this.colorMenuAnchor = null;
    this.closed = false;
    /** Distinct known values for this property: lowercase key → display text. */
    this.columnOptions = /* @__PURE__ */ new Map();
    this.vaultOptions = /* @__PURE__ */ new Map();
    const { entries, current, prop } = deps;
    for (const e of entries) {
      for (const s of valueToStrings(e.getValue(prop))) {
        const display = s.replace(/^#/, "");
        const normKey = cleanText(display).toLowerCase();
        if (normKey && !this.columnOptions.has(normKey)) {
          this.columnOptions.set(normKey, display);
        }
      }
    }
    if (deps.app && deps.app.vault) {
      const vaultFiles = deps.app.vault.getMarkdownFiles();
      for (const f of vaultFiles) {
        const normKey = f.basename.toLowerCase();
        if (!this.columnOptions.has(normKey) && !this.vaultOptions.has(normKey)) {
          const wiki = `[[${f.path.replace(/\.md$/i, "")}|${f.basename}]]`;
          this.vaultOptions.set(normKey, wiki);
        }
      }
    }
    this.selected = current.map((s) => s.replace(/^#/, ""));
    this.menu = this.build();
    this.position();
  }
  /** Whether the given node lives inside the menu or its color flyout. */
  contains(node) {
    if (!node)
      return false;
    return this.menu.contains(node) || (this.colorMenu?.contains(node) ?? false);
  }
  /** The cell element this menu is anchored to (drives click-to-toggle). */
  get anchorEl() {
    return this.deps.anchor;
  }
  /**
   * Re-point the menu at a freshly rendered cell for the same file +
   * property. `onDataUpdated` replaces every `td`, so without this the
   * anchor would dangle on a detached node and click-to-toggle (which
   * compares against the live cell) would miss. Returns whether it matched.
   */
  reanchorIfMatches(td, filePath, prop) {
    if (this.closed)
      return false;
    if (this.deps.prop !== prop || this.deps.file.path !== filePath)
      return false;
    this.deps.anchor = td;
    return true;
  }
  /** Tear the menu down. Idempotent; notifies the owner via `onClose`. */
  close() {
    if (this.closed)
      return;
    this.closed = true;
    this.closeColorMenu();
    this.menu.remove();
    this.deps.onClose();
  }
  closeColorMenu() {
    this.colorMenu?.remove();
    this.colorMenu = null;
    this.colorMenuAnchor = null;
  }
  build() {
    const { doc, isList } = this.deps;
    const menu = doc.body.createDiv({ cls: "ntn-root ntn-select-menu" });
    const currentEl = menu.createDiv({ cls: "ntn-select-current" });
    this.pillsWrap = currentEl.createDiv({ cls: "ntn-select-pills" });
    this.input = currentEl.createEl("input", {
      type: "text",
      cls: "ntn-select-input",
      attr: { placeholder: "Search or create\u2026", spellcheck: "false" }
    });
    menu.createDiv({
      cls: "ntn-select-hint",
      text: isList ? "Select options or create one" : "Select an option or create one"
    });
    this.optionsEl = menu.createDiv({ cls: "ntn-select-options" });
    this.input.addEventListener("input", () => this.renderOptions());
    this.input.addEventListener("keydown", (evt) => this.onKeydown(evt));
    this.renderPills();
    this.renderOptions();
    this.input.focus();
    return menu;
  }
  /** Empty selection deletes the property (`write` treats `null` as delete). */
  write() {
    const out = this.deps.isList ? this.selected.length ? this.selected : null : this.selected[0] ?? null;
    this.deps.write(out);
  }
  renderPills() {
    this.pillsWrap.empty();
    for (const v of this.selected) {
      const pill = this.pillsWrap.createSpan({ cls: "ntn-pill" });
      this.deps.applyColor(pill, cleanText(v));
      pill.createSpan({ text: cleanText(v) });
      const x = pill.createSpan({ cls: "ntn-pill-remove", text: "\u2715" });
      x.addEventListener("click", (evt) => {
        evt.stopPropagation();
        this.selected = this.selected.filter((s) => s !== v);
        this.write();
        this.renderPills();
        this.renderOptions();
      });
    }
  }
  pick(v) {
    if (this.deps.isList) {
      const has = this.selected.some((s) => s.toLowerCase() === v.toLowerCase());
      this.selected = has ? this.selected.filter((s) => s.toLowerCase() !== v.toLowerCase()) : [...this.selected, v];
      const normV = cleanText(v).toLowerCase();
      if (!this.columnOptions.has(normV))
        this.columnOptions.set(normV, v);
      this.write();
      this.input.value = "";
      this.renderPills();
      this.renderOptions();
      this.input.focus();
    } else {
      this.selected = [v];
      this.write();
      this.close();
    }
  }
  renderOptions() {
    this.closeColorMenu();
    this.optionsEl.empty();
    const q = this.input.value.trim();
    const ql = q.toLowerCase();
    const colVisible = [...this.columnOptions.values()].filter((o) => !ql || o.toLowerCase().includes(ql) || cleanText(o).toLowerCase().includes(ql)).sort((a, b) => cleanText(a).localeCompare(cleanText(b), void 0, { sensitivity: "base" }));
    const vaultVisible = [...this.vaultOptions.values()].filter((o) => !ql || o.toLowerCase().includes(ql) || cleanText(o).toLowerCase().includes(ql)).sort((a, b) => cleanText(a).localeCompare(cleanText(b), void 0, { sensitivity: "base" }));
    const visible = [...colVisible, ...vaultVisible];
    for (const o of visible) {
      const row = this.optionsEl.createDiv({ cls: "ntn-select-option" });
      const colorBtn = row.createSpan({
        cls: "ntn-select-color-btn",
        attr: { "aria-label": "Change color" }
      });
      const cleanName = cleanText(o);
      this.deps.applyColor(colorBtn, cleanName);
      colorBtn.addEventListener("click", (evt) => {
        evt.stopPropagation();
        this.openColorMenu(colorBtn, cleanName);
      });
      const pill = row.createSpan({ cls: "ntn-pill" });
      this.deps.applyColor(pill, cleanName);
      pill.setText(cleanName);
      const isSel = this.selected.some((s) => s.toLowerCase() === o.toLowerCase() || cleanText(s).toLowerCase() === cleanName.toLowerCase());
      if (isSel) {
        row.createSpan({ cls: "ntn-select-check", text: "\u2713" });
      }
      if (o.includes("[[")) {
        const match = o.match(/\[\[([^\]|]+)/);
        if (match && match[1]) {
          const fullPath = match[1].trim() + (match[1].toLowerCase().endsWith(".md") ? "" : ".md");
          row.setAttribute("title", fullPath);
          pill.setAttribute("title", fullPath);
          if (match[1].includes("/")) {
            const folder = match[1].substring(0, match[1].lastIndexOf("/")).trim();
            const hint = row.createSpan({ cls: "ntn-select-path-hint", text: `in ${folder}` });
            hint.setAttribute("title", fullPath);
          }
        }
      }
      const dotsBtn = row.createSpan({
        cls: "ntn-select-dots",
        text: "\u2022\u2022\u2022",
        attr: { title: "Change color" }
      });
      dotsBtn.addEventListener("click", (evt) => {
        evt.stopPropagation();
        this.openColorMenu(dotsBtn, cleanName);
      });
      row.addEventListener("click", (evt) => {
        const target = evt.target;
        if (target.hasClass("ntn-select-color-btn") || target.hasClass("ntn-select-dots"))
          return;
        this.pick(o);
      });
    }
    if (q && !this.columnOptions.has(ql) && !this.vaultOptions.has(ql)) {
      const row = this.optionsEl.createDiv({ cls: "ntn-select-option" });
      row.createSpan({ cls: "ntn-select-create", text: "Create" });
      const pill = row.createSpan({ cls: "ntn-pill" });
      this.deps.applyColor(pill, q);
      pill.setText(q);
      row.addEventListener("click", () => this.pick(q));
    }
    if (!visible.length && !q) {
      this.optionsEl.createDiv({
        cls: "ntn-select-empty",
        text: "No options yet \u2014 type to create one"
      });
    }
  }
  onKeydown(evt) {
    if (evt.key === "Escape") {
      evt.preventDefault();
      evt.stopPropagation();
      this.close();
    } else if (evt.key === "Enter") {
      const q = this.input.value.trim();
      if (q)
        this.pick(this.known.get(q.toLowerCase()) ?? q);
      else
        this.close();
    } else if (evt.key === "Backspace" && this.input.value === "" && this.deps.isList && this.selected.length) {
      this.selected = this.selected.slice(0, -1);
      this.write();
      this.renderPills();
      this.renderOptions();
    }
  }
  /** Open the color picker for a value, anchored to its row button. */
  openColorMenu(anchorEl, value) {
    if (this.colorMenu && this.colorMenuAnchor === anchorEl) {
      this.closeColorMenu();
      return;
    }
    this.closeColorMenu();
    const doc = this.deps.doc;
    const menu = doc.body.createDiv({ cls: "ntn-root ntn-color-menu" });
    this.colorMenu = menu;
    this.colorMenuAnchor = anchorEl;
    const wheelSec = menu.createDiv({ cls: "ntn-custom-color-sec" });
    wheelSec.createDiv({ cls: "ntn-color-title", text: "Custom Color Wheel" });
    const previewWrap = wheelSec.createDiv({ cls: "ntn-color-preview-wrap" });
    const previewPill = previewWrap.createSpan({ cls: "ntn-pill", text: value });
    previewPill.style.setProperty("background-color", "#2563eb", "important");
    previewPill.style.setProperty("color", "#ffffff", "important");
    const colorInput = previewWrap.createEl("input", {
      type: "color",
      cls: "ntn-color-wheel-input",
      value: "#2563eb"
    });
    const controlsRow = wheelSec.createDiv({ cls: "ntn-color-controls" });
    let selectedFg = "#ffffff";
    const fgWrap = controlsRow.createDiv({ cls: "ntn-fg-toggle-wrap" });
    const btnWhite = fgWrap.createEl("button", { cls: "ntn-fg-btn active", text: "White Text" });
    const btnBlack = fgWrap.createEl("button", { cls: "ntn-fg-btn", text: "Black Text" });
    const updatePreview = () => {
      previewPill.style.setProperty("background-color", colorInput.value, "important");
      previewPill.style.setProperty("color", selectedFg, "important");
    };
    colorInput.addEventListener("input", updatePreview);
    btnWhite.addEventListener("click", (e) => {
      e.stopPropagation();
      selectedFg = "#ffffff";
      btnWhite.addClass("active");
      btnBlack.removeClass("active");
      updatePreview();
    });
    btnBlack.addEventListener("click", (e) => {
      e.stopPropagation();
      selectedFg = "#000000";
      btnBlack.addClass("active");
      btnWhite.removeClass("active");
      updatePreview();
    });
    const applyBtn = wheelSec.createEl("button", { cls: "ntn-apply-color-btn", text: "Apply Custom Color" });
    applyBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      const spec = `${colorInput.value}|${selectedFg}`;
      this.deps.setColor(value, spec);
      this.closeColorMenu();
      this.renderPills();
      this.renderOptions();
    });
    menu.createDiv({ cls: "ntn-color-title", text: "Presets" });
    const presets = [
      // High-Vibrancy Solids (White Text)
      { name: "electric-blue", bg: "#0066FF", fg: "#ffffff", label: "Electric Blue" },
      { name: "neon-emerald", bg: "#00B060", fg: "#ffffff", label: "Neon Emerald" },
      { name: "vibrant-orange", bg: "#FF5500", fg: "#ffffff", label: "Blaze Orange" },
      { name: "deep-violet", bg: "#8000FF", fg: "#ffffff", label: "Deep Violet" },
      { name: "hot-magenta", bg: "#E6007A", fg: "#ffffff", label: "Hot Magenta" },
      { name: "crimson-red", bg: "#E51A1A", fg: "#ffffff", label: "Crimson Red" },
      { name: "bright-amber", bg: "#D97700", fg: "#ffffff", label: "Bright Amber" },
      { name: "cyan-aqua", bg: "#00A8B5", fg: "#ffffff", label: "Cyan Aqua" },
      { name: "royal-indigo", bg: "#4338CA", fg: "#ffffff", label: "Royal Indigo" },
      { name: "charcoal", bg: "#262626", fg: "#ffffff", label: "Sleek Dark" },
      // High-Vibrancy Soft Pastels (Pure Black Text)
      { name: "sky-pastel", bg: "#BAE6FD", fg: "#000000", label: "Sky Blue" },
      { name: "mint-pastel", bg: "#A7F3D0", fg: "#000000", label: "Fresh Mint" },
      { name: "peach-pastel", bg: "#FFEDD5", fg: "#000000", label: "Warm Peach" },
      { name: "lavender-pastel", bg: "#DDD6FE", fg: "#000000", label: "Soft Lavender" },
      { name: "pink-pastel", bg: "#FBCFE8", fg: "#000000", label: "Candy Pink" },
      { name: "sun-yellow", bg: "#FEF08A", fg: "#000000", label: "Sun Yellow" },
      { name: "teal-pastel", bg: "#99F6E4", fg: "#000000", label: "Turquoise" },
      { name: "rose-pastel", bg: "#FECDD3", fg: "#000000", label: "Soft Rose" },
      { name: "lime-pastel", bg: "#D9F99D", fg: "#000000", label: "Vivid Lime" },
      { name: "caramel-cream", bg: "#FEF3C7", fg: "#000000", label: "Caramel Cream" }
    ];
    const grid = menu.createDiv({ cls: "ntn-preset-grid" });
    for (const p of presets) {
      const badge = grid.createSpan({ cls: "ntn-pill ntn-preset-pill" });
      badge.style.setProperty("background-color", p.bg, "important");
      badge.style.setProperty("color", p.fg, "important");
      badge.setText(p.label);
      badge.addEventListener("click", (evt) => {
        evt.stopPropagation();
        this.deps.setColor(value, `${p.bg}|${p.fg}`);
        this.closeColorMenu();
        this.renderPills();
        this.renderOptions();
      });
    }
    this.clampToWindow(menu, anchorEl.getBoundingClientRect());
  }
  position() {
    const rect = this.deps.anchor.getBoundingClientRect();
    this.menu.setCssStyles({ minWidth: `${Math.max(rect.width, 220)}px` });
    this.clampToWindow(this.menu, rect);
  }
  /** Place a popover just below `anchorRect`, nudged to stay on screen. */
  clampToWindow(el, anchorRect) {
    const { win } = this.deps;
    el.setCssStyles({
      left: `${anchorRect.left}px`,
      top: `${anchorRect.bottom + 4}px`
    });
    const rect = el.getBoundingClientRect();
    if (rect.bottom > win.innerHeight - 8) {
      el.setCssStyles({ top: `${Math.max(8, anchorRect.top - rect.height - 4)}px` });
    }
    if (rect.right > win.innerWidth - 8) {
      el.setCssStyles({ left: `${Math.max(8, win.innerWidth - rect.width - 8)}px` });
    }
  }
};

// src/view/notion-table-view.ts
function formatDateObject(d) {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  let h = d.getHours();
  const min = String(d.getMinutes()).padStart(2, "0");
  const period = h >= 12 ? "PM" : "AM";
  h = h % 12;
  if (h === 0)
    h = 12;
  const padH = String(h).padStart(2, "0");
  return `${day}-${m}-${y} ${padH}:${min} ${period}`;
}
function extractRawDateString(value) {
  if (!value)
    return "";
  let res = "";
  if (typeof value === "string")
    res = value.trim();
  else if (value instanceof Date) {
    res = formatDateObject(value);
  } else {
    const obj = value;
    if (obj.value) {
      if (typeof obj.value === "string")
        res = obj.value.trim();
      else if (obj.value instanceof Date) {
        res = formatDateObject(obj.value);
      }
    } else if (obj.date) {
      if (typeof obj.date === "string")
        res = obj.date.trim();
      else if (obj.date instanceof Date) {
        res = formatDateObject(obj.date);
      }
    } else if (typeof obj.toString === "function") {
      const s = obj.toString().trim();
      if (s && s !== "[object Object]")
        res = s;
    } else {
      res = String(value).trim();
    }
  }
  return res === "null" || res === "undefined" ? "" : res;
}
function cleanWikilinkTitle(val) {
  if (!val)
    return "";
  const str = typeof val === "string" ? val : val.toString ? val.toString() : String(val);
  if (!str)
    return "";
  return str.replace(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g, (_, target, alias) => {
    if (alias && alias.trim())
      return alias.trim();
    const t = target.trim();
    const lastSlash = t.lastIndexOf("/");
    let name = lastSlash !== -1 ? t.substring(lastSlash + 1) : t;
    if (name.toLowerCase().endsWith(".md"))
      name = name.slice(0, -3);
    return name;
  });
}
var ObsidianNativeDatePicker = class {
  constructor(anchor, initialVal, onCommit, doc) {
    this.anchor = anchor;
    this.initialVal = initialVal;
    this.onCommit = onCommit;
    this.doc = doc;
    this.popover = null;
    this.showMonthYearSelector = false;
    this.anchorRect = anchor.getBoundingClientRect();
    const parsed = this.parseInput(initialVal);
    const now = /* @__PURE__ */ new Date();
    this.year = parsed.year ?? now.getFullYear();
    this.month = parsed.month ?? now.getMonth();
    this.selectedDay = parsed.day ?? now.getDate();
    this.selectedHour = parsed.hour ?? 12;
    this.selectedMinute = parsed.minute ?? 0;
    this.selectedPeriod = parsed.period ?? "AM";
    this.render();
  }
  parseInput(val) {
    if (!val || val === "null" || val === "undefined")
      return {};
    const str = val.trim();
    let year;
    let month;
    let day;
    let hour;
    let minute;
    let period;
    const timeMatch = str.match(/(\d{1,2}):(\d{2})(?::(\d{2}))?\s*(AM|PM)?/i);
    if (timeMatch) {
      let h = parseInt(timeMatch[1], 10);
      minute = parseInt(timeMatch[2], 10);
      if (timeMatch[4]) {
        period = timeMatch[4].toUpperCase();
        hour = h;
      } else if (h >= 12) {
        hour = h === 12 ? 12 : h - 12;
        period = "PM";
      } else {
        hour = h === 0 ? 12 : h;
        period = "AM";
      }
    }
    const isoMatch = str.match(/(\d{4})[-/.](\d{1,2})[-/.](\d{1,2})/);
    if (isoMatch) {
      year = parseInt(isoMatch[1], 10);
      month = parseInt(isoMatch[2], 10) - 1;
      day = parseInt(isoMatch[3], 10);
    } else {
      const dmyMatch = str.match(/(\d{1,2})[-/.](\d{1,2})[-/.](\d{4})/);
      if (dmyMatch) {
        day = parseInt(dmyMatch[1], 10);
        month = parseInt(dmyMatch[2], 10) - 1;
        year = parseInt(dmyMatch[3], 10);
      }
    }
    if (!year || isNaN(year)) {
      const d = new Date(str);
      if (!isNaN(d.getTime())) {
        year = d.getFullYear();
        month = d.getMonth();
        day = d.getDate();
        if (hour === void 0) {
          let h = d.getHours();
          minute = d.getMinutes();
          if (h >= 12) {
            hour = h === 12 ? 12 : h - 12;
            period = "PM";
          } else {
            hour = h === 0 ? 12 : h;
            period = "AM";
          }
        }
      }
    }
    return { year, month, day, hour, minute, period };
  }
  formatOutput() {
    const pad = (n) => String(n).padStart(2, "0");
    const y = this.year;
    const m = pad(this.month + 1);
    const d = pad(this.selectedDay);
    const h = pad(this.selectedHour);
    const min = pad(this.selectedMinute);
    return `${d}-${m}-${y} ${h}:${min} ${this.selectedPeriod}`;
  }
  render() {
    this.close();
    const pop = this.doc.body.createDiv({ cls: "ntn-native-picker-popover" });
    this.popover = pop;
    let rect = this.anchor.getBoundingClientRect();
    if (rect.width === 0 || rect.height === 0 || rect.left === 0 && rect.top === 0) {
      rect = this.anchorRect;
    } else {
      this.anchorRect = rect;
    }
    const winW = this.doc.defaultView?.innerWidth || 1200;
    const winH = this.doc.defaultView?.innerHeight || 800;
    const popLeft = Math.min(Math.max(10, rect.left), winW - 340);
    const popTop = Math.min(Math.max(10, rect.bottom + 4), winH - 280);
    pop.setCssStyles({
      left: `${popLeft}px`,
      top: `${popTop}px`
    });
    const left = pop.createDiv({ cls: "ntn-picker-left" });
    const head = left.createDiv({ cls: "ntn-picker-header" });
    const monthNames = [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December"
    ];
    const monthYear = head.createDiv({
      cls: "ntn-picker-month-year",
      text: `${monthNames[this.month]}, ${this.year} \u25BE`
    });
    monthYear.addEventListener("click", (e) => {
      e.stopPropagation();
      this.showMonthYearSelector = !this.showMonthYearSelector;
      this.render();
    });
    const arrows = head.createDiv({ cls: "ntn-picker-nav-arrows" });
    const upArrow = arrows.createSpan({ cls: "ntn-picker-arrow", text: "\u2191" });
    const downArrow = arrows.createSpan({ cls: "ntn-picker-arrow", text: "\u2193" });
    upArrow.addEventListener("click", (e) => {
      e.stopPropagation();
      this.month--;
      if (this.month < 0) {
        this.month = 11;
        this.year--;
      }
      this.render();
    });
    downArrow.addEventListener("click", (e) => {
      e.stopPropagation();
      this.month++;
      if (this.month > 11) {
        this.month = 0;
        this.year++;
      }
      this.render();
    });
    if (this.showMonthYearSelector) {
      const myContainer = left.createDiv({ cls: "ntn-picker-my-selector" });
      const mSec = myContainer.createDiv({ cls: "ntn-my-section" });
      mSec.createDiv({ cls: "ntn-my-title", text: "Select Month" });
      const mGrid = mSec.createDiv({ cls: "ntn-my-grid" });
      monthNames.forEach((name, idx) => {
        const isSel = idx === this.month;
        const btn = mGrid.createEl("button", {
          cls: `ntn-my-btn ${isSel ? "selected" : ""}`,
          text: name.slice(0, 3)
        });
        btn.addEventListener("click", (e) => {
          e.stopPropagation();
          this.month = idx;
          this.showMonthYearSelector = false;
          this.render();
        });
      });
      const ySec = myContainer.createDiv({ cls: "ntn-my-section" });
      ySec.createDiv({ cls: "ntn-my-title", text: "Select Year" });
      const yGrid = ySec.createDiv({ cls: "ntn-my-year-scroll" });
      let selectedYearEl = null;
      for (let y = 1970; y <= 2050; y++) {
        const isSel = y === this.year;
        const btn = yGrid.createEl("button", {
          cls: `ntn-my-year-btn ${isSel ? "selected" : ""}`,
          text: String(y)
        });
        if (isSel)
          selectedYearEl = btn;
        btn.addEventListener("click", (e) => {
          e.stopPropagation();
          this.year = y;
          this.showMonthYearSelector = false;
          this.render();
        });
      }
      if (selectedYearEl) {
        setTimeout(() => selectedYearEl?.scrollIntoView({ block: "center", behavior: "smooth" }), 30);
      }
    } else {
      const daysHead = left.createDiv({ cls: "ntn-picker-days-header" });
      ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"].forEach((d) => daysHead.createSpan({ text: d }));
      const grid = left.createDiv({ cls: "ntn-picker-grid" });
      const firstDayIndex = new Date(this.year, this.month, 1).getDay();
      const totalDaysInMonth = new Date(this.year, this.month + 1, 0).getDate();
      const prevMonthDays = new Date(this.year, this.month, 0).getDate();
      for (let i = firstDayIndex - 1; i >= 0; i--) {
        grid.createSpan({ cls: "ntn-picker-day other-month", text: String(prevMonthDays - i) });
      }
      for (let d = 1; d <= totalDaysInMonth; d++) {
        const isSel = d === this.selectedDay;
        const cell = grid.createSpan({
          cls: `ntn-picker-day ${isSel ? "selected" : ""}`,
          text: String(d)
        });
        cell.addEventListener("click", (e) => {
          e.stopPropagation();
          this.selectedDay = d;
          this.render();
        });
      }
      const footer = left.createDiv({ cls: "ntn-picker-footer" });
      const clearBtn = footer.createSpan({ cls: "ntn-picker-clear-btn", text: "Clear" });
      const rightFooter = footer.createDiv({ cls: "ntn-picker-right-footer" });
      const todayBtn = rightFooter.createSpan({ cls: "ntn-picker-today-btn", text: "Today" });
      const okBtn = rightFooter.createEl("button", { cls: "ntn-picker-ok-btn", text: "OK" });
      clearBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        this.onCommit(null);
        this.close();
      });
      todayBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        const now = /* @__PURE__ */ new Date();
        this.year = now.getFullYear();
        this.month = now.getMonth();
        this.selectedDay = now.getDate();
        this.render();
      });
      okBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        this.onCommit(this.formatOutput());
        this.close();
      });
    }
    pop.createDiv({ cls: "ntn-picker-divider" });
    const right = pop.createDiv({ cls: "ntn-picker-right" });
    const colHours = right.createDiv({ cls: "ntn-time-col" });
    for (let h = 1; h <= 12; h++) {
      const isSel = h === this.selectedHour;
      const cell = colHours.createDiv({
        cls: `ntn-time-cell ${isSel ? "selected" : ""}`,
        text: String(h).padStart(2, "0")
      });
      cell.addEventListener("click", (e) => {
        e.stopPropagation();
        this.selectedHour = h;
        this.render();
      });
    }
    const colMins = right.createDiv({ cls: "ntn-time-col" });
    for (let m = 0; m < 60; m++) {
      const isSel = m === this.selectedMinute;
      const cell = colMins.createDiv({
        cls: `ntn-time-cell ${isSel ? "selected" : ""}`,
        text: String(m).padStart(2, "0")
      });
      cell.addEventListener("click", (e) => {
        e.stopPropagation();
        this.selectedMinute = m;
        this.render();
      });
    }
    const colPeriod = right.createDiv({ cls: "ntn-time-col" });
    ["PM", "AM"].forEach((p) => {
      const isSel = p === this.selectedPeriod;
      const cell = colPeriod.createDiv({
        cls: `ntn-time-cell ${isSel ? "selected" : ""}`,
        text: p
      });
      cell.addEventListener("click", (e) => {
        e.stopPropagation();
        this.selectedPeriod = p;
        this.render();
      });
    });
    const onOutside = (e) => {
      if (this.popover && !this.popover.contains(e.target) && !this.anchor.contains(e.target)) {
        this.close();
      }
    };
    const onKeydown = (e) => {
      if (e.key === "Escape") {
        e.preventDefault();
        e.stopPropagation();
        this.close();
      }
    };
    setTimeout(() => {
      this.doc.addEventListener("mousedown", onOutside);
      this.doc.addEventListener("keydown", onKeydown);
    }, 50);
    this._onOutside = onOutside;
    this._onKeydown = onKeydown;
  }
  close() {
    if (this.popover) {
      if (this._onOutside)
        this.doc.removeEventListener("mousedown", this._onOutside);
      if (this._onKeydown)
        this.doc.removeEventListener("keydown", this._onKeydown);
      this.popover.remove();
    }
  }
};
var NotionTableView = class extends import_obsidian4.BasesView {
  constructor(controller, parentEl) {
    super(controller);
    this.columnWidths = /* @__PURE__ */ new Map();
    this.collapsedGroups = /* @__PURE__ */ new Set();
    this.expandedPaths = /* @__PURE__ */ new Set();
    this.type = NOTION_TABLE_VIEW;
    /** True while the toolbar's New button is rerouted to the page panel. */
    this.newButtonPatched = false;
    this.queryCtrl = controller;
    this.rootEl = parentEl.createDiv({ cls: "ntn-root" });
    this.register(() => this.closeSelectMenu());
    this.registerDomEvent(this.rootEl.doc, "mousedown", (evt) => {
      if (!this.selectEditor)
        return;
      const target = evt.target;
      if (this.selectEditor.contains(target))
        return;
      if (this.selectEditor.anchorEl.contains(target))
        return;
      this.closeSelectMenu();
    }, { capture: true });
    this.patchToolbarNew();
  }
  buildGroupTree(entries) {
    const nodeMap = /* @__PURE__ */ new Map();
    const titleToNode = /* @__PURE__ */ new Map();
    for (const entry of entries) {
      const node = {
        entry,
        children: [],
        level: 0,
        hasChildren: false
      };
      nodeMap.set(entry.file.path, node);
      titleToNode.set(entry.file.basename.toLowerCase(), node);
    }
    const roots = [];
    for (const node of nodeMap.values()) {
      const fm = this.app.metadataCache.getFileCache(node.entry.file)?.frontmatter || {};
      const rawParent = fm.parent || fm.Parent || fm.parent_item || fm.subtask_of;
      let parentStr = null;
      if (rawParent) {
        const str = String(rawParent).trim();
        const match = str.match(/^\[\[([^\]|]+)(?:\|[^\]]+)?\]\]$/);
        parentStr = match ? match[1].trim() : str.replace(/\.md$/i, "").trim();
      }
      if (parentStr) {
        const parentNode = titleToNode.get(parentStr.toLowerCase());
        if (parentNode && parentNode.entry.file.path !== node.entry.file.path) {
          parentNode.children.push(node);
          parentNode.hasChildren = true;
        } else {
          roots.push(node);
        }
      } else {
        roots.push(node);
      }
    }
    function setLevels(nodes, lvl) {
      for (const n of nodes) {
        n.level = lvl;
        if (n.children.length > 0) {
          setLevels(n.children, lvl + 1);
        }
      }
    }
    setLevels(roots, 0);
    return roots;
  }
  openGroupColorPicker(anchorEl, groupKey) {
    const doc = this.rootEl.doc;
    const existing = doc.querySelector(".ntn-group-color-flyout");
    if (existing)
      existing.remove();
    const flyout = doc.body.createDiv({ cls: "ntn-select-menu ntn-group-color-flyout" });
    flyout.createDiv({ cls: "ntn-color-title", text: "Group Color" });
    const rect = anchorEl.getBoundingClientRect();
    flyout.setCssStyles({
      position: "fixed",
      top: `${rect.bottom + 4}px`,
      left: `${rect.left}px`,
      zIndex: "1000"
    });
    const colors = [
      { name: "default", label: "Default" },
      { name: "gray", label: "Gray" },
      { name: "brown", label: "Brown" },
      { name: "orange", label: "Orange" },
      { name: "yellow", label: "Yellow" },
      { name: "green", label: "Green" },
      { name: "blue", label: "Blue" },
      { name: "purple", label: "Purple" },
      { name: "pink", label: "Pink" },
      { name: "red", label: "Red" }
    ];
    const grid = flyout.createDiv({ cls: "ntn-color-grid" });
    for (const c of colors) {
      const btn = grid.createEl("button", { cls: "ntn-color-option" });
      const sq = btn.createSpan({ cls: "ntn-color-sq" });
      applyPillColor(sq, c.name, /* @__PURE__ */ new Map([[c.name.toLowerCase(), c.name]]));
      btn.createSpan({ text: c.label });
      btn.addEventListener("click", (e) => {
        e.stopPropagation();
        this.setPinnedColor(groupKey, c.name);
        flyout.remove();
        this.onDataUpdated();
      });
    }
    const closeHandler = (e) => {
      if (!flyout.contains(e.target)) {
        flyout.remove();
        doc.removeEventListener("mousedown", closeHandler);
      }
    };
    setTimeout(() => doc.addEventListener("mousedown", closeHandler), 50);
  }
  attachColumnDragDrop(th, propKey) {
    th.addEventListener("dragstart", (evt) => {
      evt.dataTransfer?.setData("text/plain", propKey);
    });
    th.addEventListener("dragover", (evt) => {
      evt.preventDefault();
      th.addClass("ntn-th-drag-over");
    });
    th.addEventListener("dragleave", () => {
      th.removeClass("ntn-th-drag-over");
    });
    th.addEventListener("drop", (evt) => {
      evt.preventDefault();
      th.removeClass("ntn-th-drag-over");
      const draggedProp = evt.dataTransfer?.getData("text/plain");
      if (draggedProp && draggedProp !== propKey) {
        const currentOrder = [...this.config.getOrder()];
        const fromIdx = currentOrder.indexOf(draggedProp);
        const toIdx = currentOrder.indexOf(propKey);
        if (fromIdx !== -1 && toIdx !== -1) {
          currentOrder.splice(fromIdx, 1);
          currentOrder.splice(toIdx, 0, draggedProp);
          if (typeof this.config.setOrder === "function") {
            this.config.setOrder(currentOrder);
          }
          this.onDataUpdated();
        }
      }
    });
  }
  attachResizeHandle(th, propKey) {
    const handle = th.createDiv({ cls: "ntn-col-resize-handle" });
    handle.addEventListener("mousedown", (e) => {
      e.preventDefault();
      e.stopPropagation();
      this.wasResizingJustNow = true;
      const startX = e.clientX;
      const startW = th.offsetWidth;
      handle.addClass("resizing");
      const doc = this.rootEl.doc;
      const onMouseMove = (moveEvt) => {
        const delta = moveEvt.clientX - startX;
        const newW = Math.max(60, startW + delta);
        th.setCssStyles({ width: `${newW}px` });
        this.columnWidths.set(propKey, newW);
      };
      const onMouseUp = () => {
        handle.removeClass("resizing");
        doc.removeEventListener("mousemove", onMouseMove);
        doc.removeEventListener("mouseup", onMouseUp);
        setTimeout(() => {
          this.wasResizingJustNow = false;
        }, 200);
      };
      doc.addEventListener("mousemove", onMouseMove);
      doc.addEventListener("mouseup", onMouseUp);
    });
  }
  buildUnifiedHierarchyTree(entries) {
    const entryIndexMap = /* @__PURE__ */ new Map();
    entries.forEach((e, idx) => entryIndexMap.set(e.file.path.toLowerCase(), idx));
    const nodeMap = /* @__PURE__ */ new Map();
    const titleToNode = /* @__PURE__ */ new Map();
    for (const entry of entries) {
      const node = {
        entry,
        children: [],
        level: 0,
        hasChildren: false
      };
      nodeMap.set(entry.file.path.toLowerCase(), node);
      titleToNode.set(entry.file.basename.toLowerCase(), node);
    }
    const roots = [];
    const userParentProp = String(this.config.get("parentProperty") || "").toLowerCase().trim();
    const normUserParent = userParentProp.replace(/[_\\-\\s]+/g, "");
    for (const node of nodeMap.values()) {
      const fm = this.app.metadataCache.getFileCache(node.entry.file)?.frontmatter || {};
      let rawParent = null;
      if (userParentProp) {
        for (const k of Object.keys(fm)) {
          const normK = k.toLowerCase().replace(/[_\\-\\s]+/g, "");
          if (k.toLowerCase().trim() === userParentProp || normK === normUserParent) {
            rawParent = fm[k];
            break;
          }
        }
      }
      if (!rawParent) {
        rawParent = fm["parent item"] || fm["Parent Item"] || fm["parent_item"] || fm["Parent_Item"] || fm.parent || fm.Parent || fm["parent-item"] || fm.subtask_of || fm["subtask of"];
        if (!rawParent) {
          for (const k of Object.keys(fm)) {
            const normK = k.toLowerCase().replace(/[_\\-\\s]+/g, "");
            if (normK === "parentitem" || normK === "parent" || normK === "subtaskof" || normK === "parenttask") {
              rawParent = fm[k];
              break;
            }
          }
        }
      }
      let parentStr = null;
      if (rawParent) {
        parentStr = cleanWikilinkTitle(rawParent);
      }
      if (parentStr) {
        const parentNode = titleToNode.get(parentStr.toLowerCase()) || nodeMap.get(parentStr.toLowerCase() + ".md");
        if (parentNode && parentNode.entry.file.path.toLowerCase() !== node.entry.file.path.toLowerCase()) {
          parentNode.children.push(node);
          parentNode.hasChildren = true;
        } else {
          roots.push(node);
        }
      } else {
        roots.push(node);
      }
    }
    const self = this;
    function sortNodes(nodes) {
      nodes.sort((a, b) => {
        if (self.sortCol && self.sortDir) {
          let valA = null;
          let valB = null;
          if (self.sortCol === "title") {
            valA = a.entry.file.basename;
            valB = b.entry.file.basename;
          } else {
            valA = a.entry.getValue(self.sortCol);
            valB = b.entry.getValue(self.sortCol);
          }
          const strA = valA !== null && valA !== void 0 ? cleanWikilinkTitle(valA).toLowerCase() : "";
          const strB = valB !== null && valB !== void 0 ? cleanWikilinkTitle(valB).toLowerCase() : "";
          const numA = Number(strA);
          const numB = Number(strB);
          let cmp = 0;
          if (!isNaN(numA) && !isNaN(numB) && strA !== "" && strB !== "") {
            cmp = numA - numB;
          } else {
            cmp = strA.localeCompare(strB, void 0, { numeric: true, sensitivity: "base" });
          }
          if (cmp !== 0)
            return self.sortDir === "desc" ? -cmp : cmp;
        }
        const idxA = entryIndexMap.get(a.entry.file.path.toLowerCase()) ?? 999999;
        const idxB = entryIndexMap.get(b.entry.file.path.toLowerCase()) ?? 999999;
        return idxA - idxB;
      });
      for (const n of nodes) {
        if (n.children.length > 0) {
          sortNodes(n.children);
        }
      }
    }
    sortNodes(roots);
    function assignDepth(nodes, lvl) {
      for (const n of nodes) {
        n.level = lvl;
        if (n.children.length > 0) {
          assignDepth(n.children, lvl + 1);
        }
      }
    }
    assignDepth(roots, 0);
    return roots;
  }
  async openInSidePanel(file) {
    void this.app.workspace.openLinkText(file.path, "", "split");
  }
  onDataUpdated() {
    this.patchToolbarNew();
    const root = this.rootEl;
    root.empty();
    root.toggleClass("ntn-wrap", this.config.get("wrapCells") !== false);
    root.toggleClass("ntn-vlines", this.config.get("verticalLines") !== false);
    const rawProps = this.customColumnOrder || this.config.getOrder();
    const displayProps = rawProps.filter((p) => {
      const bare = p.split(".").slice(1).join(".").toLowerCase();
      return p !== "file.name" && p !== "file.basename" && p !== "note.name" && bare !== "file.name";
    });
    this.pills = computePillProps(displayProps, this.data.data, this.config, this.app);
    this.pinnedColors = parsePinnedColors(this.config.get("pinnedColors"));
    const table = root.createEl("table", { cls: "ntn-table" });
    const thead = table.createEl("thead");
    const headRow = thead.createEl("tr");
    const thTitle = headRow.createEl("th", { cls: "ntn-th ntn-col-title" });
    const titleW = this.columnWidths.get("title") || 240;
    thTitle.setCssStyles({ width: `${titleW}px` });
    thTitle.createSpan({ cls: "ntn-th-icon", text: "Aa" });
    thTitle.createSpan({ text: "Name" });
    if (this.sortCol === "title") {
      thTitle.createSpan({ cls: "ntn-th-sort-icon", text: this.sortDir === "asc" ? " \u25B2" : " \u25BC" });
    }
    this.attachResizeHandle(thTitle, "title");
    thTitle.addEventListener("click", (evt) => {
      if (this.wasResizingJustNow)
        return;
      const target = evt.target;
      if (target.hasClass("ntn-col-resize-handle"))
        return;
      if (this.sortCol === "title") {
        if (this.sortDir === "asc") {
          this.sortDir = "desc";
        } else {
          this.sortCol = null;
          this.sortDir = null;
        }
      } else {
        this.sortCol = "title";
        this.sortDir = "asc";
      }
      this.onDataUpdated();
    });
    for (const prop of displayProps) {
      const th = headRow.createEl("th", { cls: "ntn-th" });
      th.setAttribute("draggable", "true");
      th.createSpan({ text: this.config.getDisplayName(prop) });
      if (this.sortCol === prop) {
        th.createSpan({ cls: "ntn-th-sort-icon", text: this.sortDir === "asc" ? " \u25B2" : " \u25BC" });
      }
      const savedW = this.columnWidths.get(prop) || 180;
      th.setCssStyles({ width: `${savedW}px` });
      this.attachResizeHandle(th, prop);
      th.addEventListener("click", (evt) => {
        if (this.wasResizingJustNow)
          return;
        const target = evt.target;
        if (target.hasClass("ntn-col-resize-handle"))
          return;
        if (this.sortCol === prop) {
          if (this.sortDir === "asc") {
            this.sortDir = "desc";
          } else {
            this.sortCol = null;
            this.sortDir = null;
          }
        } else {
          this.sortCol = prop;
          this.sortDir = "asc";
        }
        this.onDataUpdated();
      });
      th.addEventListener("dragstart", (evt) => {
        this.draggedProp = prop;
        th.addClass("ntn-dragging");
        if (evt.dataTransfer) {
          evt.dataTransfer.effectAllowed = "move";
          evt.dataTransfer.setData("text/plain", prop);
        }
      });
      th.addEventListener("dragend", () => {
        this.draggedProp = null;
        th.removeClass("ntn-dragging");
        headRow.querySelectorAll(".ntn-th").forEach((el) => el.removeClass("ntn-drag-over"));
      });
      th.addEventListener("dragover", (evt) => {
        evt.preventDefault();
        if (evt.dataTransfer) {
          evt.dataTransfer.dropEffect = "move";
        }
        if (this.draggedProp && this.draggedProp !== prop) {
          th.addClass("ntn-drag-over");
        }
      });
      th.addEventListener("dragleave", () => {
        th.removeClass("ntn-drag-over");
      });
      th.addEventListener("drop", (evt) => {
        evt.preventDefault();
        th.removeClass("ntn-drag-over");
        const fromProp = this.draggedProp || evt.dataTransfer?.getData("text/plain");
        const toProp = prop;
        if (fromProp && toProp && fromProp !== toProp) {
          const fromIdx = displayProps.indexOf(fromProp);
          const toIdx = displayProps.indexOf(toProp);
          if (fromIdx !== -1 && toIdx !== -1) {
            const updated = [...displayProps];
            const [removed] = updated.splice(fromIdx, 1);
            updated.splice(toIdx, 0, removed);
            this.customColumnOrder = updated;
            try {
              if (typeof this.config.setOrder === "function") {
                this.config.setOrder(updated);
              } else if (typeof this.config.set === "function") {
                this.config.set("order", updated);
              }
            } catch (e) {
              console.debug("Bases config setOrder non-fatal fallback", e);
            }
            this.onDataUpdated();
          }
        }
      });
    }
    const allEntries = this.data.data;
    let finalEntries;
    if (this.sortCol && this.sortDir) {
      const allNodes = [];
      const traverse = (nodes) => {
        for (const n of nodes) {
          allNodes.push(n);
          if (n.children.length > 0)
            traverse(n.children);
        }
      };
      const roots = this.buildUnifiedHierarchyTree(allEntries);
      traverse(roots);
      allNodes.sort((a, b) => {
        let valA = null;
        let valB = null;
        if (this.sortCol === "title") {
          valA = a.entry.file.basename;
          valB = b.entry.file.basename;
        } else {
          valA = a.entry.getValue(this.sortCol);
        }
        if (this.sortCol !== "title") {
          valB = b.entry.getValue(this.sortCol);
        }
        const strA = valA !== null && valA !== void 0 ? cleanWikilinkTitle(valA).toLowerCase() : "";
        const strB = valB !== null && valB !== void 0 ? cleanWikilinkTitle(valB).toLowerCase() : "";
        const numA = Number(strA);
        const numB = Number(strB);
        let cmp = 0;
        if (!isNaN(numA) && !isNaN(numB) && strA !== "" && strB !== "") {
          cmp = numA - numB;
        } else {
          cmp = strA.localeCompare(strB, void 0, { numeric: true, sensitivity: "base" });
        }
        return this.sortDir === "desc" ? -cmp : cmp;
      });
      for (const n of allNodes) {
        n.children = [];
        n.hasChildren = false;
        n.level = 0;
      }
      finalEntries = allNodes;
    } else {
      finalEntries = this.buildUnifiedHierarchyTree(allEntries);
    }
    const tbody = table.createEl("tbody");
    for (const rootNode of finalEntries) {
      this.renderNodeRow(tbody, rootNode, displayProps);
    }
    const newRow = root.createDiv({ cls: "ntn-new-row" });
    newRow.createSpan({ cls: "ntn-new-plus", text: "+" });
    newRow.createSpan({ text: "New" });
    newRow.addEventListener("click", () => void this.createAndOpenPage());
  }
  renderNodeRow(tbody, node, props) {
    const entry = node.entry;
    const isExpanded = this.expandedPaths.has(entry.file.path);
    const tr = tbody.createEl("tr", { cls: "ntn-row" });
    const titleTd = tr.createEl("td", { cls: "ntn-td ntn-col-title" });
    const titleWrap = titleTd.createDiv({ cls: "ntn-title-wrap" });
    if (node.level > 0) {
      const spacer = titleWrap.createSpan({ cls: "ntn-indent-spacer" });
      spacer.style.width = `${node.level * 20}px`;
    }
    if (node.hasChildren) {
      const toggleBtn = titleWrap.createSpan({
        cls: `ntn-toggle-btn ${isExpanded ? "expanded" : ""}`
      });
      toggleBtn.innerHTML = `<svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><polyline points="9 18 15 12 9 6"></polyline></svg>`;
      toggleBtn.addEventListener("click", (evt) => {
        evt.stopPropagation();
        if (this.expandedPaths.has(entry.file.path)) {
          this.expandedPaths.delete(entry.file.path);
        } else {
          this.expandedPaths.add(entry.file.path);
        }
        this.onDataUpdated();
      });
    } else {
      const emptyBtn = titleWrap.createSpan({ cls: "ntn-toggle-btn" });
      emptyBtn.style.opacity = "0";
    }
    titleWrap.createSpan({ cls: "ntn-page-icon", text: "\u{1F4C4}" });
    const link = titleWrap.createSpan({
      cls: "ntn-title-text",
      text: entry.file.basename
    });
    link.addEventListener("click", (evt) => {
      const mode = this.config.get("openMode");
      if (mode === "split") {
        void this.app.workspace.openLinkText(entry.file.path, "", "split");
      } else if (mode === "panel") {
        this.openPagePanel(entry.file);
      } else {
        void this.app.workspace.openLinkText(entry.file.path, "", evt.ctrlKey || evt.metaKey);
      }
    });
    if (node.hasChildren) {
      titleWrap.createSpan({ cls: "ntn-subcount", text: String(node.children.length) });
    }
    const openBtn = titleWrap.createSpan({ cls: "ntn-open-btn", text: "OPEN" });
    openBtn.addEventListener("click", (evt) => {
      evt.stopPropagation();
      const mode = this.config.get("openMode");
      if (mode === "split") {
        void this.app.workspace.openLinkText(entry.file.path, "", "split");
      } else if (mode === "panel") {
        this.openPagePanel(entry.file);
      } else {
        void this.app.workspace.openLinkText(entry.file.path, "", true);
      }
    });
    for (const prop of props) {
      const td = tr.createEl("td", { cls: "ntn-td" });
      this.renderCell(td, entry, prop);
    }
    if (isExpanded && node.children.length > 0) {
      for (const child of node.children) {
        this.renderNodeRow(tbody, child, props);
      }
    }
  }
  isPillProp(prop) {
    const bare = prop.includes(".") ? prop.split(".").slice(1).join(".").toLowerCase() : prop.toLowerCase();
    const userParent = String(this.config.get("parentProperty") || "").toLowerCase().trim();
    if (userParent && (bare === userParent || bare.replace(/[_\\-\\s]+/g, "") === userParent.replace(/[_\\-\\s]+/g, "")))
      return true;
    for (const p of this.pills.pillProps) {
      const pBare = p.includes(".") ? p.split(".").slice(1).join(".").toLowerCase() : p.toLowerCase();
      if (pBare === bare)
        return true;
    }
    return bare === "parent_item" || bare === "parent item" || bare === "parent" || bare === "year" || bare === "tags" || bare === "status";
  }
  /** Strictly check if a property is a Date property via MetadataTypeManager, value type, name, or ISO format. */
  isDateProperty(prop, propName, value) {
    if (value !== null && (value?.constructor?.name === "DateValue" || value instanceof Date)) {
      return true;
    }
    if (prop.startsWith("file.ctime") || prop.startsWith("file.mtime")) {
      return true;
    }
    const bare = propName.includes(".") ? propName.split(".").pop() : propName;
    const lowBare = bare.toLowerCase().trim();
    const mtm = this.app?.metadataTypeManager;
    const info = mtm?.getPropertyInfo?.(lowBare);
    const metaType = typeof info === "string" ? info : info?.widget ?? info?.type;
    if (metaType === "date" || metaType === "datetime") {
      return true;
    }
    const normalized = lowBare.replace(/[_\.-\s]+/g, " ");
    const keywords = ["date", "due", "deadline", "ctime", "mtime", "created", "completion"];
    for (const kw of keywords) {
      if (normalized === kw || normalized.startsWith(kw + " ") || normalized.endsWith(" " + kw) || normalized.includes(" " + kw + " ")) {
        return true;
      }
    }
    if (value !== null && typeof value === "object" && "toString" in value) {
      const strVal = String(value).trim();
      if (/^\d{4}-\d{2}-\d{2}/.test(strVal)) {
        return true;
      }
    }
    return false;
  }
  renderCell(td, entry, prop) {
    const value = entry.getValue(prop);
    const isFileStat = prop.startsWith("file.ctime") || prop.startsWith("file.mtime") || prop.startsWith("file.path") || prop.startsWith("file.folder");
    const editable = !isFileStat;
    const propName = prop.includes(".") ? prop.split(".").slice(1).join(".") : prop;
    const isDatePropName = this.isDateProperty(prop, propName, value);
    const isPill = !isDatePropName && (this.isPillProp(prop) || value !== null && String(value).includes("[["));
    if (isPill) {
      const wrap = td.createDiv({ cls: "ntn-pills" });
      const items = valueToStrings(value);
      for (const item of items) {
        const cleanedText = cleanWikilinkTitle(item).replace(/^#/, "");
        if (cleanedText) {
          const pill = wrap.createSpan({ cls: "ntn-pill" });
          this.applyPillColor(pill, cleanedText);
          pill.setText(cleanedText);
          if (item.includes("[[")) {
            const match = item.match(/\[\[([^\]|]+)/);
            if (match && match[1]) {
              pill.setAttribute("title", match[1].trim());
            }
          }
        }
      }
      if (editable) {
        td.addClass("ntn-editable");
        td.addEventListener(
          "click",
          () => this.openSelectEditor(td, entry, prop, propName)
        );
        this.selectEditor?.reanchorIfMatches(td, entry.file.path, prop);
      }
      return;
    }
    if (value instanceof import_obsidian4.BooleanValue) {
      const cb = td.createEl("input", { type: "checkbox", cls: "ntn-checkbox" });
      cb.checked = value.isTruthy();
      if (editable) {
        cb.addEventListener("change", () => {
          void this.writeProperty(entry.file, propName, cb.checked);
        });
      } else {
        cb.disabled = true;
      }
      return;
    }
    const cellEl = td.createDiv({ cls: "ntn-cell" });
    const isFileProp = prop.startsWith("file.ctime") || prop.startsWith("file.mtime");
    const isDate = isDatePropName;
    if (isDate) {
      const rawDateStr = extractRawDateString(value);
      const textToShow = rawDateStr && rawDateStr !== "null" && rawDateStr !== "undefined" ? rawDateStr : "";
      cellEl.setText(textToShow);
    } else if (value !== null) {
      const s = String(value).trim();
      if (s !== "null" && s !== "undefined") {
        if (s.startsWith("[[") && s.endsWith("]]")) {
          cellEl.setText(cleanWikilinkTitle(s));
        } else {
          value.renderTo(cellEl, this.app.renderContext);
        }
      }
    }
    if (!isFileProp) {
      td.addClass("ntn-editable");
      const kind = value instanceof import_obsidian4.NumberValue ? "number" : isDate ? "date" : "text";
      const handleEdit = (evt) => {
        if (!isDate) {
          const target = evt.target;
          if (target.closest("a"))
            return;
        }
        evt.preventDefault();
        evt.stopPropagation();
        const rawVal = isDate ? extractRawDateString(value) || cellEl.textContent?.trim() || "" : value ? value.toString() : "";
        this.editCell(td, entry, propName, rawVal, kind);
      };
      td.addEventListener("dblclick", handleEdit);
      td.addEventListener("click", handleEdit);
    }
  }
  /** Swap a cell's content for an input; commit on Enter/blur, cancel on Esc. */
  editCell(td, entry, propName, current, kind) {
    if (td.querySelector(".ntn-input"))
      return;
    if (kind === "date") {
      const initialVal2 = extractRawDateString(current) || td.textContent?.trim() || "";
      new ObsidianNativeDatePicker(
        td,
        initialVal2,
        (formattedStr) => {
          void this.writeProperty(entry.file, propName, formattedStr);
        },
        this.rootEl.doc
      );
      return;
    }
    const rect = td.getBoundingClientRect();
    const multiline = kind === "text" && rect.height > 40;
    td.empty();
    let initialVal = current;
    const input = multiline ? td.createEl("textarea", { cls: "ntn-input ntn-textarea" }) : td.createEl("input", {
      type: kind === "number" ? "number" : "text",
      cls: "ntn-input"
    });
    input.setCssStyles({
      width: `${Math.max(rect.width, 140)}px`,
      height: `${Math.max(rect.height, 30)}px`
    });
    input.value = initialVal;
    input.focus();
    input.select();
    let committed = false;
    const commit = () => {
      if (committed)
        return;
      committed = true;
      const raw = input.value.trim();
      if (raw === current) {
        this.onDataUpdated();
        return;
      }
      let out = raw || null;
      if (kind === "number") {
        const n = Number(raw);
        out = raw === "" ? null : Number.isNaN(n) ? raw : n;
      }
      void this.writeProperty(entry.file, propName, out);
    };
    input.addEventListener("blur", commit);
    input.addEventListener("keydown", (ev) => {
      const evt = ev;
      if (evt.key === "Enter") {
        commit();
      } else if (evt.key === "Escape") {
        committed = true;
        this.onDataUpdated();
      }
    });
  }
  async writeProperty(file, propName, value) {
    if (!propName || propName === "null" || propName === "undefined" || !propName.trim())
      return;
    try {
      await this.app.fileManager.processFrontMatter(file, (fm) => {
        for (const [k, v] of Object.entries(fm)) {
          if (k === "null" || k === "undefined" || v === null || v === "null" || v === void 0 || Array.isArray(v) && (v.length === 0 || v.length === 1 && (v[0] === null || v[0] === "null" || v[0] === ""))) {
            delete fm[k];
          }
        }
        const keyToUse = Object.keys(fm).find((k) => k.toLowerCase() === propName.toLowerCase()) || propName;
        const isNullVal = value === null || value === "" || value === void 0 || value === "null" || Array.isArray(value) && (value.length === 0 || value.length === 1 && (value[0] === null || value[0] === "null" || value[0] === ""));
        if (isNullVal) {
          delete fm[keyToUse];
        } else {
          fm[keyToUse] = value;
        }
      });
      this.onDataUpdated();
    } catch (e) {
      console.error(`${LOG_PREFIX} failed to write property`, propName, e);
      new import_obsidian4.Notice(`Couldn't update "${propName}".`);
      this.onDataUpdated();
    }
  }
  /**
   * Reroute the core toolbar's New button to the page panel while this
   * view is active. The button lives on the query controller, outside this
   * view's DOM, so its menu's `open` is shadowed on the instance and
   * restored on unload. `newItemMenu` is internal API — if it ever moves,
   * the guard below simply leaves the core behavior untouched (and the
   * footer "+ New" falls back to its own capture flow).
   */
  patchToolbarNew() {
    if (this.newButtonPatched)
      return;
    const menu = this.queryCtrl.newItemMenu;
    if (!menu || typeof menu.open !== "function" || typeof menu.close !== "function") {
      return;
    }
    const orig = menu.open.bind(menu);
    const patched = async (name, fmProc) => {
      if (import_obsidian4.Platform.isPhone)
        return orig(name, fmProc);
      let created;
      const ref = this.app.vault.on("create", (file) => {
        if (file instanceof import_obsidian4.TFile)
          created = file;
      });
      const body = this.rootEl.doc.body;
      body.addClass("ntn-hide-new-popover");
      try {
        await orig(name, fmProc);
      } finally {
        this.app.vault.offref(ref);
        menu.close();
        body.removeClass("ntn-hide-new-popover");
      }
      if (created)
        this.openPagePanel(created);
    };
    menu.open = patched;
    this.newButtonPatched = true;
    this.register(() => {
      menu.open = orig;
      this.newButtonPatched = false;
    });
  }
  /**
   * "+ New" flow: create the note through the core Bases flow — so it lands
   * in the configured folder and gets the frontmatter implied by the view's
   * filters — then edit it in the centered Notion-style page panel instead
   * of the small popover Obsidian anchors to the toolbar's New button.
   */
  async createAndOpenPage() {
    if (import_obsidian4.Platform.isPhone || this.newButtonPatched) {
      await this.createFileForView();
      return;
    }
    let created;
    const ref = this.app.vault.on("create", (file) => {
      if (file instanceof import_obsidian4.TFile)
        created = file;
    });
    try {
      await this.createFileForView();
    } finally {
      this.app.vault.offref(ref);
    }
    if (!created)
      return;
    const doc = this.rootEl.doc;
    if (doc.querySelector(".bases-new-item-popover"))
      doc.body.click();
    this.openPagePanel(created);
  }
  /** Open a note centered in the Notion-style page panel. */
  openPagePanel(file) {
    new NotePageModal(this.app, file, {
      applyColor: (pill, text) => this.applyPillColor(pill, text),
      write: (f, propName, value) => this.writeProperty(f, propName, value),
      isPillProp: (name) => this.pills.pillProps.has(`note.${name}`),
      isListProp: (name) => this.pills.listProps.has(`note.${name}`),
      openSelect: (opts) => this.openSelectAt(opts),
      reanchorSelect: (anchor, filePath, propName) => void this.selectEditor?.reanchorIfMatches(
        anchor,
        filePath,
        `note.${propName}`
      ),
      closeSelect: () => this.closeSelectMenu()
    }).open();
  }
  /** Color a pill element using this view's pinned-color overrides. */
  applyPillColor(pill, text) {
    applyPillColor(pill, text, this.pinnedColors);
  }
  /** Open the Notion-style select editor for a pill cell of the table. */
  openSelectEditor(td, entry, prop, propName) {
    this.openSelectAt({
      anchor: td,
      file: entry.file,
      propName,
      current: valueToStrings(entry.getValue(prop)),
      isList: this.pills.listProps.has(prop)
    });
  }
  /**
   * Open the select editor anchored anywhere — a table cell or a property
   * row of the page panel. Known values always come from the live query
   * result; lifetime stays with the view (outside-click / Esc / unload).
   */
  openSelectAt(opts) {
    if (this.selectEditor?.anchorEl === opts.anchor) {
      this.closeSelectMenu();
      return;
    }
    this.closeSelectMenu();
    const prop = `note.${opts.propName}`;
    this.selectEditor = new SelectEditor({
      app: this.app,
      doc: this.rootEl.doc,
      win: this.rootEl.win,
      anchor: opts.anchor,
      entries: this.data.data,
      file: opts.file,
      current: opts.current,
      prop,
      isList: opts.isList,
      applyColor: (pill, text) => this.applyPillColor(pill, text),
      write: (value) => void this.writeProperty(opts.file, opts.propName, value).then(() => opts.onWrite?.()),
      setColor: (value, colorName) => this.setPinnedColor(value, colorName),
      onClose: () => {
        this.selectEditor = null;
      }
    });
  }
  /**
   * Pin a value to a specific Notion color. Updates the live map for instant
   * feedback in the open editor, then persists into the `pinnedColors` view
   * option (replacing any prior entry for the same value) so it survives
   * reloads and is editable from the view settings too.
   */
  setPinnedColor(value, colorSpec) {
    const bare = value.replace(/^#/, "");
    const key = bare.toLowerCase();
    let colorObj;
    if (colorSpec.includes("|") || colorSpec.startsWith("#")) {
      const parts = colorSpec.split("|");
      const bg = parts[0].trim();
      let fg = parts[1] ? parts[1].trim() : "#ffffff";
      if (fg === "white" || fg === "light")
        fg = "#ffffff";
      if (fg === "black" || fg === "dark")
        fg = "#111827";
      colorObj = {
        name: "custom",
        lightBg: bg,
        lightFg: fg,
        darkBg: bg,
        darkFg: fg
      };
    } else {
      colorObj = colorByName(colorSpec.toLowerCase());
    }
    if (!colorObj)
      return;
    this.pinnedColors.set(key, colorObj);
    const raw = this.config.get("pinnedColors");
    const list = Array.isArray(raw) ? raw.map((s) => String(s)) : [];
    const kept = list.filter((item) => {
      const m = item.match(/^(.+?)\s*[=:]\s*(.+)$/);
      return m ? m[1].trim().replace(/^#/, "").toLowerCase() !== key : true;
    });
    kept.push(`${bare}=${colorSpec}`);
    this.config.set("pinnedColors", kept);
    this.onDataUpdated();
  }
  closeSelectMenu() {
    this.selectEditor?.close();
    this.selectEditor = null;
  }
};

// src/main.ts
var NotionBasesPlugin = class extends import_obsidian5.Plugin {
  async onload() {
    if (typeof this.registerBasesView !== "function") {
      new import_obsidian5.Notice("GoodBases: requires Obsidian 1.10.0+ (registerBasesView API missing).", 8e3);
      return;
    }
    const ok = this.registerBasesView(NOTION_TABLE_VIEW, {
      name: "Notion-style table",
      icon: "lucide-table-2",
      factory: (controller, containerEl) => new NotionTableView(controller, containerEl),
      options: buildViewOptions
    });
    if (!ok) {
      new import_obsidian5.Notice("GoodBases: view registration failed. Is the Bases core plugin enabled?", 8e3);
    }
  }
};
